(define (product term a next b)
  (if (> a b)
    1
    (* (term a)
       (product term (next a) next b))))
(define (factorial n)
  (define (identity x) x)
  (define (inc x) (+ 1 x))
  (product identity 1 inc n))
(define (pi n)
  (define (fractions-pair i)
    (/ (* i (+ 2 i))
       (* (+ 1 i) (+ 1 i))))
  (define (inc-by-2 i)
    (+ 2 i))
  (* 4
     (product fractions-pair 2 inc-by-2 n)))
