(define (iterative-improve close-enough? next)
  (define (try guess)
    (newline)
    (display next)
    (if (close-enough? guess next)
      next
      (try next)))
  try)
(define (fixed-point f first-guess)
  (define tolerance 0.00001)
  (define (close-enough? v1 v2)
    (< (abs (- v1 v2)) tolerance))
  (define ((next (f guess))))
  ((iterative-improve close-enough? next) first-guess))
(define (average-damp proc)
  (lambda (x)
    (/ (+ x
          (proc x))
       2)))
(define (sqrt x)
  (define (transformed y)
    (/ x
       y))
  (fixed-point (average-damp transformed) 1.0))
