(define (make-point x y)
  (cons x y))
(define (x-point point)
  (car point))
(define (y-point point)
  (cdr point))
(define (make-segment start end)
  (cons start end))
(define (start-segment segment)
  (car segment))
(define (end-segment segment)
  (cdr segment))
(define (print-point p)
  (newline)
  (display "(")
  (display (x-point p))
  (display ",")
  (display (y-point p))
  (display ")"))
(define (midpoint-segment segment)
  (average-point (start-segment segment)
                 (end-segment segment)))
(define (average-point first second)
  (make-point (average (x-point first)
                       (x-point second))
              (average (y-point first)
                       (y-point second))))
(define (average a b)
  (/ (+ a b)
     2))
