(define (equal? a b)
  (cond ((and (symbol? a)
              (symbol? b))
         (eq? a b))
        ((and (eq? a '())
              (eq? b '()))
         #t)
        ((and (pair? a)
              (pair? b))
         (and (eq? (car a)
                   (car b))
              (equal? (cdr a)
                      (cdr b))))
        (else #f)))
