(meeting ?m (Friday ?time))
(rule (meeting-time ?person ?day-and-time)
      (and (job ?person (?department . ?))
           (or (meeting ?department ?day-and-time)
               (meeting whole-company ?day-and-time))))
(meeting-time (Hacker Alyssa P.) (Wednesday ?time))
