(define (lazy-cons x y)
  (lambda (m) (m x y)))
(define (lazy-car z)
  (z (lambda (p q) p)))
(define (lazy-cdr z)
  (z (lambda (p q) q)))
(define (display-list lazy-list)
  (define (display-up-to n lazy-list)
    (if (= n 0)
        'done
        (begin (display (lazy-car lazy-list))
               (display " ")
               (display-up-to (- n 1) (lazy-cdr lazy-list)))))
  (display "(")
  (display-up-to 3 lazy-list)
  (display "...")
  (display ")")
  (newline))
(display-list (lazy-cons 'a (lazy-cons 'b (lazy-cons 'c (lazy-cons 'd '())))))

