; library
(define (make-lambda parameters body)
  (cons 'lambda (cons parameters body)))
; new syntax for defines
(define define-variable '(answer <- 42))
(define define-procedure '(proc <- (x) (+ x 1)))
(define (definition? exp)
  (eq? '<- (cadr exp)))
(define (definition-variable exp)
  (car exp))
(define (definition-value exp)
  (if (list? (caddr exp))
    (make-lambda (caddr exp)
                 (cdddr exp))
    (caddr exp)))
(display (definition-variable define-variable))
(newline)
(display (definition-value define-variable))
(newline)
(display (definition-variable define-procedure))
(newline)
(display (definition-value define-procedure))
(newline)
