(load "chapter5.2.scm")
(define (make-save-b inst machine stack pc)
  (let ((reg-name (stack-inst-reg-name inst)))
    (let ((reg (get-register machine
                             reg-name)))
      (lambda ()
        (push stack (list reg-name (get-contents reg)))
        (advance-pc pc)))))
(define (make-restore-b inst machine stack pc)
  (let ((reg-name (stack-inst-reg-name inst)))
    (let ((reg (get-register machine
                             reg)))
      (lambda ()
        (let ((popped (pop stack)))
          (if (eq? reg-name (car popped))
              (set-contents! reg (cadr popped))
              (error "pushed one register but popped on another -- MAKE-RESTORE" (list reg-name popped))))
        (advance-pc pc)))))
